import type { Product, Category, Supplier, InventoryAlert, PizzaSize, PizzaTopping, Order } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Pizzas",
    description: "Fresh made pizzas with various toppings",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Appetizers",
    description: "Starters and side dishes",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Beverages",
    description: "Soft drinks, juices, and other beverages",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "Desserts",
    description: "Sweet treats and desserts",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "5",
    name: "Ingredients",
    description: "Pizza ingredients and toppings",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "Italian Ingredients Co.",
    contactPerson: "Marco Rossi",
    email: "marco@italianingredients.com",
    phone: "+1-555-0123",
    address: "123 Pizza St, Little Italy, NY 10013",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Fresh Produce Ltd.",
    contactPerson: "Sarah Green",
    email: "sarah@freshproduce.com",
    phone: "+1-555-0456",
    address: "456 Farm Ave, Fresh Valley, CA 90210",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Dairy & Cheese Suppliers",
    contactPerson: "John Cheddar",
    email: "john@dairycheese.com",
    phone: "+1-555-0789",
    address: "789 Cheese Blvd, Dairy Town, WI 53706",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const pizzaSizes: PizzaSize[] = [
  { id: "small", name: "Small", diameter: 10, basePrice: 12.99 },
  { id: "medium", name: "Medium", diameter: 12, basePrice: 15.99 },
  { id: "large", name: "Large", diameter: 14, basePrice: 18.99 },
  { id: "xlarge", name: "X-Large", diameter: 16, basePrice: 21.99 },
]

export const pizzaToppings: PizzaTopping[] = [
  // Meats
  { id: "pepperoni", name: "Pepperoni", price: 2.5, category: "meat", isActive: true },
  { id: "sausage", name: "Italian Sausage", price: 2.5, category: "meat", isActive: true },
  { id: "ham", name: "Ham", price: 2.25, category: "meat", isActive: true },
  { id: "bacon", name: "Bacon", price: 2.75, category: "meat", isActive: true },
  { id: "chicken", name: "Grilled Chicken", price: 3.0, category: "meat", isActive: true },

  // Vegetables
  { id: "mushrooms", name: "Mushrooms", price: 1.75, category: "vegetable", isActive: true },
  { id: "peppers", name: "Bell Peppers", price: 1.5, category: "vegetable", isActive: true },
  { id: "onions", name: "Red Onions", price: 1.25, category: "vegetable", isActive: true },
  { id: "olives", name: "Black Olives", price: 1.75, category: "vegetable", isActive: true },
  { id: "tomatoes", name: "Fresh Tomatoes", price: 1.5, category: "vegetable", isActive: true },
  { id: "spinach", name: "Fresh Spinach", price: 1.75, category: "vegetable", isActive: true },

  // Cheese
  { id: "mozzarella", name: "Extra Mozzarella", price: 2.0, category: "cheese", isActive: true },
  { id: "parmesan", name: "Parmesan", price: 2.25, category: "cheese", isActive: true },
  { id: "feta", name: "Feta Cheese", price: 2.5, category: "cheese", isActive: true },
]

export const mockProducts: Product[] = [
  // Base Pizzas
  {
    id: "1",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    sku: "PIZ-001",
    barcode: "1234567890123",
    category: "Pizzas",
    price: 15.99,
    cost: 8.5,
    stock: 0, // Made to order
    minStock: 0,
    maxStock: 0,
    unit: "pizza",
    isActive: true,
    supplierId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni pizza with mozzarella cheese",
    sku: "PIZ-002",
    barcode: "1234567890124",
    category: "Pizzas",
    price: 17.99,
    cost: 9.25,
    stock: 0,
    minStock: 0,
    maxStock: 0,
    unit: "pizza",
    isActive: true,
    supplierId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },

  // Appetizers
  {
    id: "3",
    name: "Garlic Bread",
    description: "Fresh baked garlic bread with herbs",
    sku: "APP-001",
    barcode: "1234567890125",
    category: "Appetizers",
    price: 6.99,
    cost: 3.5,
    stock: 25,
    minStock: 10,
    maxStock: 50,
    unit: "piece",
    isActive: true,
    supplierId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    name: "Buffalo Wings",
    description: "Spicy buffalo chicken wings with ranch dip",
    sku: "APP-002",
    barcode: "1234567890126",
    category: "Appetizers",
    price: 12.99,
    cost: 7.0,
    stock: 15,
    minStock: 8,
    maxStock: 30,
    unit: "order",
    isActive: true,
    supplierId: "2",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },

  // Beverages
  {
    id: "5",
    name: "Coca-Cola",
    description: "Classic Coca-Cola soft drink",
    sku: "BEV-001",
    barcode: "1234567890127",
    category: "Beverages",
    price: 2.99,
    cost: 1.25,
    stock: 48,
    minStock: 20,
    maxStock: 100,
    unit: "can",
    isActive: true,
    supplierId: "2",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },

  // Ingredients (for inventory tracking)
  {
    id: "6",
    name: "Pizza Dough",
    description: "Fresh pizza dough balls",
    sku: "ING-001",
    barcode: "1234567890128",
    category: "Ingredients",
    price: 0, // Not sold directly
    cost: 1.5,
    stock: 45,
    minStock: 20,
    maxStock: 100,
    unit: "ball",
    isActive: true,
    supplierId: "1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "7",
    name: "Mozzarella Cheese",
    description: "Fresh mozzarella cheese for pizzas",
    sku: "ING-002",
    barcode: "1234567890129",
    category: "Ingredients",
    price: 0,
    cost: 4.5,
    stock: 12,
    minStock: 15,
    maxStock: 50,
    unit: "lb",
    isActive: true,
    supplierId: "3",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "8",
    name: "Pepperoni",
    description: "Sliced pepperoni for pizzas",
    sku: "ING-003",
    barcode: "1234567890130",
    category: "Ingredients",
    price: 0,
    cost: 6.0,
    stock: 8,
    minStock: 10,
    maxStock: 25,
    unit: "lb",
    isActive: true,
    supplierId: "2",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
]

export const mockInventoryAlerts: InventoryAlert[] = [
  {
    id: "1",
    productId: "7",
    type: "low_stock",
    message: "Mozzarella Cheese is running low (12 lbs remaining, minimum: 15 lbs)",
    isRead: false,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    productId: "8",
    type: "low_stock",
    message: "Pepperoni is running low (8 lbs remaining, minimum: 10 lbs)",
    isRead: false,
    createdAt: new Date("2024-01-15"),
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-001",
    customerId: "1",
    items: [
      {
        id: "1",
        productId: "1",
        productName: "Margherita Pizza",
        quantity: 1,
        unitPrice: 15.99,
        customization: {
          size: "medium",
          crust: "thin",
          toppings: ["mozzarella"],
          specialInstructions: "Extra basil",
        },
      },
    ],
    subtotal: 15.99,
    tax: 1.28,
    total: 17.27,
    orderType: "dine-in",
    status: "preparing",
    paymentStatus: "paid",
    createdAt: new Date("2024-01-15T12:30:00"),
    estimatedReadyTime: new Date("2024-01-15T12:45:00"),
    customerPhone: "+1-555-0123",
  },
]
